config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get '/privacy' => 'homes#privacy'
  get '/term'    => 'homes#term'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
      post :soft_delete
    end
    resources :trainings, only: [:show]
    resources :user_infos, only: [:index, :edit, :update, :destroy]
  end
  resources :records do
    resources :training_records, only: [:create, :update, :destroy]
  end
  post 'training_records/new_record_create' => 'training_records#new_record_create'
  resources :tweets, only: [:index, :show, :edit, :update, :create, :destroy] do
    resources :favorites, only: [:create, :destroy]
    resources :tweet_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :parts, only: [] do
    resources :trainings, only: [:index]
  end
  resources :notifications, only: :index do
    collection do
      delete :destroy_all
    end
 end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :tweet
  belongs_to :user

  validates :user_id,  presence: true
  validates :tweet_id, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @favorite = current_user.favorites.create(tweet_id: params[:tweet_id])
    @tweet.create_notification_by(current_user) # 通知の作成
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
    end
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @favorite = Favorite.find_by(user_id: current_user.id, tweet_id: @tweet.id)
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite_btn.html.erb
<% if favo = Favorite.find_by(user_id: current_user.id, tweet_id: obj.id) %>
    <%= link_to "♥#{obj.favorites.count}", tweet_favorite_path(obj.id, favo.id), {method: :delete, class: "favorited", remote: true} %>
<% else %>
     <%= link_to "♥#{obj.favorites.count}", tweet_favorites_path(obj.id), {method: :post, class: "favorite", remote: true} %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite-btn-<%= @tweet.id %>').html('<%= j(render 'favorites/favorite_btn', obj: @tweet) %>');

app/views/favorites/destroy.js.erb
$('#favorite-btn-<%= @tweet.id %>').html('<%= j(render 'favorites/favorite_btn', obj: @tweet) %>');