config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get '/privacy' => 'homes#privacy'
  get '/term'    => 'homes#term'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
      post :soft_delete
    end
    resources :trainings, only: [:show]
    resources :user_infos, only: [:index, :edit, :update, :destroy]
  end
  resources :records do
    resources :training_records, only: [:create, :update, :destroy]
  end
  post 'training_records/new_record_create' => 'training_records#new_record_create'
  resources :tweets, only: [:index, :show, :edit, :update, :create, :destroy] do
    resources :favorites, only: [:create, :destroy]
    resources :tweet_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :parts, only: [] do
    resources :trainings, only: [:index]
  end
  resources :notifications, only: :index do
    collection do
      delete :destroy_all
    end
 end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  has_many :favorites,      dependent: :destroy
  has_many :tweet_comments, dependent: :destroy
  has_many :notifications,  dependent: :destroy

  validates :user_id,  presence: true
  validates :content,  presence: true, length: { maximum: 300 }

  attachment :image

  acts_as_taggable_on :tags

  def self.get_self_and_following_tweets(user)
    Tweet.includes([:user]).where("user_id IN (?) OR user_id = ?", user.following_ids, user.id)
  end
  
  # いいね の通知作成を実行するメソッド
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(item_id: id, visited_id: user_id, action: 'like')
    notification.save if notification.valid?
  end
  
  # コメントの通知作成を実行するメソッド
  def create_notification_comment!(current_user, comment_id)
    # 自分以外のコメント済みユーザーを取得。その後、全員に通知を作成。
    tmp_ids = TweetComment.where(tweet_id: id).where.not(user_id: current_user.id).pluck(:user_id).push(self.user_id)
    tmp_ids.each do |tmp_id|
      save_notification_comment!(current_user, comment_id, tmp_id)
    end
    if tmp_ids.blank?
      save_notification_comment!(current_user, comment_id, user_id)
    end
  end
  
  # コメントの通知作成メソッド
  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(item_id: id, comment_id: comment_id, visited_id: visited_id, action: 'comment')
    # 自分の投稿に対する自分のコメントは通知済みとする
    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:destroy]

  def index
    @tweet = Tweet.new
    if params[:tag].present?
      @tweets = Tweet.includes([:user]).tagged_with(params[:tag]).page(params[:page]).per(15)
    else
      # 自分+フォロー中ユーザーの投稿一覧
      tweets = Tweet.get_self_and_following_tweets(current_user)
      @tweets = tweets.order(created_at: :desc).page(params[:page]).per(15)
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweet_comment = TweetComment.new(user_id: current_user.id, tweet_id: @tweet.id)
    @tweet_comments = TweetComment.includes([:user]).where(tweet_id: @tweet.id)
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    
    # Natural Language API にて投稿のポジティブネガティブ数を判定
    @tweet.score = Language.get_data(tweet_params[:content])
    
    if @tweet.save
      if @tweet.image #画像投稿がある場合のみ。
         # Vision AI にて自動取得したタグを追加する。
        tags = Vision.get_image_data(@tweet.image)
        tags.each do |tag|
          @tweet.tag_list.push (tag)
        end
        @tweet.save
      end
      
      tweets = Tweet.get_self_and_following_tweets(current_user)
      @tweets = tweets.order(created_at: :desc).page(params[:page]).per(15)
      redirect_to tweets_path
    else
      tweets = Tweet.get_self_and_following_tweets(current_user)
      @tweets = tweets.order(created_at: :desc).page(params[:page]).per(15)
      render 'tweets/index'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    tweets = Tweet.get_self_and_following_tweets(current_user)
    @tweets = tweets.order(created_at: :desc).page(params[:page]).per(15)
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.js
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content, :image, :tag_list)
  end

  def ensure_correct_user
    @tweet = Tweet.find(params[:id])
    @user = @tweet.user
    unless @user == current_user
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_new_tweet_form.html.erb
<%= render 'layouts/errors', obj: resource %>
<h4 class='text-center bg-danger text-white rounded-top py-1 font-weight-bold'>新規投稿</h4>
<div class="border-bottom m-3 bg-white rounded p-2">
  <%= form_with model: resource, local: true, method: :post do |f| %>
    <div class="field d-flex align-items-center mb-1">
      <%= attachment_image_tag current_user, :image, fallback: 'no_image.jpg', size: '40x40', class: 'rounded-circle mr-2' %>
      <%= f.text_area :content, class: 'tweet-text-area tweet-content-form', placeholder: '筋トレ仲間に熱い想いを届けよう！'  %>
    </div>
    <div class='field d-flex align-items-center mb-1'>
      <i class="fas fa-tags font-tags mr-2 px-1"></i>
      <%= f.text_field :tag_list, value: resource.tag_list.join(' '), class: 'tag_form', id: "tag_area" %>
    </div>
    <div class="field d-flex align-items-center mb-1" style='overflow-x: hidden;'>
      <i class="fas fa-image font-images mr-2 px-2 pt-1"></i>
      <%= f.attachment_field :image %>
    </div>
    <div class='text-center'>
      <%= f.submit "投稿する", class: 'btn btn-success p-1 ml-auto mt-2 mb-0 mr-3 px-4' %>
    </div>
  <% end %>
</div>

app/views/tweets/_tweet_comment_form.html.erb
<h2 class='text-center mt-3'>コメント投稿</h2>
<%= render 'layouts/errors', obj: obj2 %>
<%= form_with model:[obj1, obj2], remote: true do |f| %>
<div class="field">
  <%= f.label :image %><br />
  <%= f.attachment_field :image, id: 'tweet_comment_image_form' %>
</div>
<div class="field">
  <%= f.label :content %><br />
  <%= f.text_area :content, id: 'tweet_comment_content_form' %>
</div>
<div class="actions">
  <%= f.submit "投稿する" %>
</div>
<% end %>

app/views/tweets/_tweet_index.html.erb
<div class="main-layout-container rounded-lg shadow-lg bg-warning border">
  <h4 class='main-layout-title text-center bg-danger text-white rounded-top py-1 font-weight-bold'>
    <% if params[:tag] %>
      <%= "検索結果 （##{params[:tag]}）" %>
    <% else %>
      <% if @user && (@user != current_user) %>
        <%= "#{@user.name} さんのツイート一覧" %>
      <% else %>
        タイムライン
      <% end %>
    <% end %>
  </h4>
  <div class="tweet-box  mb-2 mt-1 rounded">
    <% obj.each do |tweet| %>
    <div class="tweet border-bottom m-3 bg-white rounded">
      <div class='tweet-main'>
        <div class='tweet-left ml-3'>
          <%= link_to user_path(tweet.user) do %>
            <%= attachment_image_tag tweet.user, :image, fallback: 'no_image.jpg', size: '40x40', class: 'ml-1 mr-3 my-3 rounded-circle' %><span class='font-weight-bold'><%= "#{tweet.user.name}" %></span>
          <% end %>
          <div style='overflow-wrap: break-word; max-width: 98%;'><%= tweet.content %></div>
        </div>
        <div class='tweet-right mr-3 d-flex align-items-center ml-3 my-3'>
          <%= attachment_image_tag tweet, :image, size: '100x100' %>
        </div>
        <div class='ml-3'>
          <% tweet.tag_counts.each do |tag| %>
            <%= link_to "##{tag.name}(#{tag.taggings_count})", tweets_path(tag: tag.name), {class: 'mr-2', data: {"turbolinks" => false}} %>
          <% end %>
        </div>
      </div>
      <div class='tweet-info d-flex mt-3'>
        <% if tweet.score %>
          <% if tweet.score >= 0.5  %>
            <div class='tweet-positive-parameter ml-2' style='color: red;'> 感情指数 <i class="far fa-grin-squint"></i> <%= tweet.score %></div>
          <% elsif tweet.score > 0 %>
            <div class='tweet-positive-parameter ml-2' style='color: green;'> 感情指数 <i class="far fa-grin-alt"></i> <%= tweet.score %></div>
          <% elsif  -0.5 < tweet.score %>
            <div class='tweet-positive-parameter ml-2' style='color: green;'> 感情指数 <i class="far fa-meh"></i> <%= tweet.score %></div>
          <% else %>
            <div class='tweet-positive-parameter ml-2' style='color: blue;'> 感情指数 <i class="far fa-tired"></i> <%= tweet.score %></div>
          <% end %>
        <% end %>
        <div id="favorite-btn-<%= tweet.id %>" class='ml-auto mr-1'><%= render 'favorites/favorite_btn', obj: tweet %></div>
        <div class='tweet-comment mx-1'><%= link_to "コメント#{tweet.tweet_comments.count}", tweet_path(tweet.id), {id: "tweet-#{tweet.id}-show-link"} %></div>
        <% if tweet.user == current_user %>
          <div class='mx-1'><%= link_to '削除する', tweet_path(tweet), method: :delete, remote: true, id: "tweet-#{tweet.id}-delete-link" %></div>
        <% end %>
        <div class='tweet-time mx-1'><%= "#{tweet.created_at.strftime('%Y/%m/%d %H:%M:%S')}" %></div>
      </div>
    </div>
    <% end %>
  </div>
  <div class='kaminari d-flex justify-content-center'>
    <%= paginate obj %>
  </div>
</div>

app/views/tweets/destroy.js.erb
$('.tweets-container').html("<%= j( render 'tweets/tweet_index', obj: @tweets ) %>");

app/views/tweets/index.html.erb
<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-lg-4 offset-lg-1 user-info mb-5 mt-3">
      <%= render 'layouts/user_sidebar', obj: current_user %>
    </div>
    <div class="col-lg-6">
      <div class="new-tweet-container rounded-lg shadow bg-warning border mb-3">
        <%= render 'tweets/new_tweet_form', resource: @tweet %>
      </div>
      <div class='tweets-container'>
        <%= render 'tweets/tweet_index', obj: @tweets %>
      </div>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="container-fluid mt-3">
  <div class="row">
    <div class="col-lg-4 offset-lg-1 user-info mb-5 mt-3">
      <%= render 'layouts/user_sidebar', obj: current_user %>
    </div>
    <div class="col-lg-6">
      <h2 class='text-center'>ツイート詳細</h2>
      <div class="tweet border-bottom">
        <%= link_to user_path(@tweet.user) do %>
        <%= attachment_image_tag @tweet.user, :image, fallback: 'no_image.jpg', size: '40x40', class: 'mb-3 rounded-circle' %><span><%= "#{@tweet.user.name}" %></span>
        <% end %>
        <p><%= @tweet.content %></p>
        <%= attachment_image_tag @tweet, :image, size: '100x100', class: 'mb-3' %>
        <div id="favorite-btn-<%= @tweet.id %>"><%= render 'favorites/favorite_btn', obj: @tweet %></div>
        <div class='tweet-comment'><%= "コメント#{@tweet.tweet_comments.count}件" %></div>
      </div>
      <div class="tweet-comments-box">
        <%= render partial: 'tweet_comments/tweet_comments_list', locals: {obj1: @tweet_comments, obj2: @tweet} %>
      </div>
      <div class="tweet-comment-form-box">
        <%= render partial: 'tweets/tweet_comment_form', locals: {obj1: @tweet, obj2: @tweet_comment} %>
      </div>
    </div>
  </div>
</div>