config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get '/privacy' => 'homes#privacy'
  get '/term'    => 'homes#term'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
      post :soft_delete
    end
    resources :trainings, only: [:show]
    resources :user_infos, only: [:index, :edit, :update, :destroy]
  end
  resources :records do
    resources :training_records, only: [:create, :update, :destroy]
  end
  post 'training_records/new_record_create' => 'training_records#new_record_create'
  resources :tweets, only: [:index, :show, :edit, :update, :create, :destroy] do
    resources :favorites, only: [:create, :destroy]
    resources :tweet_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :parts, only: [] do
    resources :trainings, only: [:index]
  end
  resources :notifications, only: :index do
    collection do
      delete :destroy_all
    end
 end
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  has_many :training_records, dependent: :destroy

  validates :user_id, presence: true
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit]

  def index
    @records = current_user.records.page(params[:page]).per(15)
    @record = Record.find_by(created_at: Time.zone.now.all_day,
                             user_id: current_user.id) || Record.new
  end

  def show
    @record = Record.find(params[:id]) || Record.new
    @training_record = TrainingRecord.new
    @training_records = TrainingRecord.includes([:training]).where(record_id: @record.id)
  end

  def new
    @record = Record.find_by(created_at: Time.zone.now.all_day, user_id: current_user.id)
    if @record # 今日の記録が作成済みの場合
      redirect_to record_path(@record)
    else # 今日の記録が未作成の場合
      @today_date = Date.current.strftime('%Y/%m/%d') # 本日の日付を取得
      @record = Record.new
      @training_record = TrainingRecord.new
    end
  end

  def edit
    @record = Record.find(params[:id])
    @training_records = TrainingRecord.includes([:training]).where(record_id: @record.id)
    @training_record = TrainingRecord.new
  end

  private

  def ensure_correct_user
    @record = Record.find(params[:id])
    @user = @record.user
    unless @user == current_user
      redirect_to record_path(@record)
    end
  end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/edit.html.erb
<div class="container-fluid">
    <div class='row'>
      <div class=' col-lg-10 offset-lg-1 mt-3'>
      <h2 class='text-center my-4'><span class='training-note-title-part'><%= @record.created_at.strftime('%Y/%m/%d') %></span><span class='training-note-title-part'>トレーニング内容編集</span></h2>
      <%= render 'layouts/errors', obj: @training_record %>
      <%= form_with model: [@record, TrainingRecord.new], local: true do |f| %>
        <div class='mt-3'>
          <div class='mb-2'>
            <% category_options = Part.order(:id).map{|c| [c.name, c.id, data: { children_path: part_trainings_path(c)}] } %>
            <%= f.select :part_id, category_options, {include_blank: 'ーー部位を選択ーー' }, class: 'select-parent' %>
          </div>
          <div class='mb-3'>
            <% sub_categories = Part.try(:trainings) || [] %>
            <% sub_category_options = sub_categories.map{ |c| [c.name, c.id] } %>
            <%= f.select :training_id, sub_category_options, { include_blank: 'ーー部位別トレーニング一覧ーー' }, class: 'select-children' %>
          </div>
        </div>
        <div class='d-flex mb-4 align-items-center'>
          <div>
            <%= f.number_field :weight, class: 'training_number_form', step: '0.1' %><span class='training-form-unit-part'>kg</span>
          </div>
          
          <div>
            <%= f.number_field :rep, class: 'ml-2 training_number_form', step: '0.1' %><span class='training-form-unit-part'>回</span>
          </div>
          
          <div>
            <%= f.number_field :set, class: 'ml-2 training_number_form', step: '0.1' %><span class='training-form-unit-part'>セット</span>
          </div>
          <div>
            <%= f.submit '記録する', class: 'btn btn-primary ml-1' %>
          </div>
        </div>
      <% end %>
      <table class="table taining-edit-table" style="width: 100%;">
        <thead>
          <th width="25%">トレーニング</th>
          <th width="25%">重量</th></th>
          <th width="25%">レップ</th>
          <th width="25%">セット</th>
        </thead>
        <tbody>
          <% @training_records.each do |t_record| %>
          <%= form_with model: [@record, t_record], local: true do |f| %>
          <tr>
            <td width="25%"><%= t_record.training.name %></td>
            <td width="25%"><%= f.number_field :weight, value: t_record.weight, id: "weight-field-#{t_record.id}", class: 'training_number_form_edit' %><span class='training-form-unit-part'>kg</span></td>
            <td width="25%"><%= f.number_field :rep, value: t_record.rep, id: "rep-field-#{t_record.id}", class: 'training_number_form_edit'%><span class='training-form-unit-part'>回</span></td>
            <td width="25%"><%= f.number_field :set, value: t_record.set, id: "set-field-#{t_record.id}", class: 'training_number_form_edit' %><span class='training-form-unit-part'>セット</span></td>
          </tr>
          <% if @record.user == current_user %>
          <tr>
            <td width="25%" style='border: none;'></td>
            <td width="25%" style='border: none;'></td>
            <td width="50%" style='border: none;' colspan='2' class='text-right'>
              <%= f.submit '変更', class: "btn btn-success ml-auto p-0", id: "update-btn-#{t_record.id}" %>
              <%= link_to '削除', record_training_record_path(@record.id, t_record.id), method: :delete, class: 'btn btn-danger edit-delete-btn p-0' %>
            </td>
            
          </tr>
          <% end %>
          <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  

app/views/records/index.html.erb
<div class="container-fluid">
  <div class='row'>
    <div class='col-lg-8 offset-lg-2'>
      <h2 class='text-center my-3'>トレーニングノート</h2>
      <%= link_to '今日のトレーニングを記録する', new_record_path, data: {"turbolinks" => false} %>
      <table class="table">
        <thead>
          <th>日付</th>
          <th></th>
        </thead>
        <tbody>
          <% @records.each do |record| %>
          <tr>
            <td><%= record.created_at.strftime('%Y年%m月%d日') %></td>
            <td><%= link_to '詳細', record_path(record.id), {class: 'btn btn-success', data: {"turbolinks" => false}} %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
     <div class='kaminari d-flex justify-content-center'>
      <%= paginate @records %>
    </div>
    </div>
  </div>
</div>

app/views/records/new.html.erb
<div class="container-fluid">
  <div class='row'>
    <div class=' col-lg-10 offset-lg-1 mt-3'>
    <h2 class='text-center my-4'><span class='training-note-title-part'><%= @today_date %></span><span class='training-note-title-part'>トレーニングノート</span></h2>
    <%= render 'layouts/errors', obj: @training_record %>
    <%= form_with model: @training_record, url: training_records_new_record_create_path, local: true do |f| %>
      <div>
        <div class='mb-2'>
          <% category_options = Part.order(:id).map{|c| [c.name, c.id, data: { children_path: part_trainings_path(c)}] } %>
          <%= f.select :part_id, category_options, {include_blank: 'ーー部位を選択ーー' }, class: 'select-parent' %>
        </div>
        <div class='mb-3'>
          <% sub_categories = Part.try(:trainings) || [] %>
          <% sub_category_options = sub_categories.map{ |c| [c.name, c.id] } %>
          <%= f.select :training_id, sub_category_options, { include_blank: 'ーー部位別トレーニング一覧ーー' }, class: 'select-children' %>
        </div>
      </div>
      <div class='d-flex mb-4 align-items-center'>
        <div>
          <%= f.number_field :weight, class: 'training_number_form', step: '0.1' %><span class='training-form-unit-part'>kg</span>
        </div>
        
        <div>
          <%= f.number_field :rep, class: 'ml-2 training_number_form', step: '0.1' %><span class='training-form-unit-part'>回</span>
        </div>
        
        <div>
          <%= f.number_field :set, class: 'ml-2 training_number_form', step: '0.1' %><span class='training-form-unit-part'>セット</span>
        </div>
        <div>
          <%= f.submit '記録する', class: 'btn btn-primary ml-1' %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
  <div class="row">
    <div class='col-lg-10 offset-lg-1'>
      <table class="table">
        <thead>
          <th>トレーニング名</th>
          <th>重量</th></th>
          <th>レップ</th>
          <th>セット</th>
        </thead>
        <tbody>
          <% @record.training_records.each do |t_record| %>
          <tr>
            <td><%= t_record.training.name %></td>
            <td><%= t_record.weight %><span class='training-form-unit-part'>kg</span></td>
            <td><%= t_record.rep %><span class='training-form-unit-part'>回</span></td>
            <td><%= t_record.set %><span class='training-form-unit-part'>セット</span></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  

app/views/records/show.html.erb
<div class="container-fluid">
  <% if current_user == @record.user %>
  <div class='justify-content-start mt-3'>
    <%= link_to '<<トレーニング一覧へ戻る', records_path %>
  </div>
  <% end %>
  <div class='row'>
    <div class=' col-lg-10 offset-lg-1 mt-3'>
    <% if current_user != @record.user  %>
      <h2 class='text-center my-4'><%= "#{@record.user.name} さん"%></h2>
    <% end %>
    <h2 class='text-center my-4'><span class='training-note-title-part'><%= @record.created_at.strftime('%Y/%m/%d') %></span><span class='training-note-title-part'>トレーニング詳細</span></h2>
    <% if @record.user == current_user %>
      <%= link_to 'トレーニング内容の編集はこちら', edit_record_path(@record), data: {"turbolinks" => false} %>
    <% end %>
    <%= render 'layouts/errors', obj: @training_record %>
    <% if current_user == @record.user %>
      <%= form_with model: [@record,@training_record], local: true do |f| %>
        <div class='mt-3'>
          <div class='mb-2'>
            <% category_options = Part.order(:id).map{|c| [c.name, c.id, data: { children_path: part_trainings_path(c)}] } %>
            <%= f.select :part_id, category_options, {include_blank: 'ーー部位を選択ーー' }, class: 'select-parent' %>
          </div>
          <div class='mb-3'>
            <% sub_categories = Part.try(:trainings) || [] %>
            <% sub_category_options = sub_categories.map{ |c| [c.name, c.id] } %>
            <%= f.select :training_id, sub_category_options, { include_blank: 'ーー部位別トレーニング一覧ーー' }, class: 'select-children' %>
          </div>
        </div>
        <div class='d-flex mb-4 align-items-center'>
          <div>
            <%= f.number_field :weight, class: 'training_number_form', step: '0.1' %><span class='training-form-unit-part'>kg</span>
          </div>
          
          <div>
            <%= f.number_field :rep, class: 'ml-2 training_number_form', step: '0.1' %><span class='training-form-unit-part'>回</span>
          </div>
          
          <div>
            <%= f.number_field :set, class: 'ml-2 training_number_form', step: '0.1' %><span class='training-form-unit-part'>セット</span>
          </div>
          <div>
            <%= f.submit '記録する', class: 'btn btn-primary ml-1' %>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
  <div class="row">
    <div class='col-lg-10 offset-lg-1'>
      <table class="table">
        <thead>
          <th>トレーニング名</th>
          <th>重量</th></th>
          <th>レップ</th>
          <th>セット</th>
        </thead>
        <tbody>
          <% @training_records.each do |t_record| %>
          <tr>
            <td><%= link_to "#{t_record.training.name}", user_training_path(@record.user.id, t_record.training_id) %></td>
            <td><%= t_record.weight %><span class='training-form-unit-part'>kg</span></td>
            <td><%= t_record.rep %><span class='training-form-unit-part'>回</span></td>
            <td><%= t_record.set %><span class='training-form-unit-part'>セット</span></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  