config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks',
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'
  get '/privacy' => 'homes#privacy'
  get '/term'    => 'homes#term'
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
      post :soft_delete
    end
    resources :trainings, only: [:show]
    resources :user_infos, only: [:index, :edit, :update, :destroy]
  end
  resources :records do
    resources :training_records, only: [:create, :update, :destroy]
  end
  post 'training_records/new_record_create' => 'training_records#new_record_create'
  resources :tweets, only: [:index, :show, :edit, :update, :create, :destroy] do
    resources :favorites, only: [:create, :destroy]
    resources :tweet_comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :parts, only: [] do
    resources :trainings, only: [:index]
  end
  resources :notifications, only: :index do
    collection do
      delete :destroy_all
    end
 end
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= "#{obj.errors.count}件のエラーがあります。ご確認ください。" %></h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_user_sidebar.html.erb
<div class="user-image-profile-box d-flex justify-content-center">
  <div class="user-image-box mr-1">
    <%= attachment_image_tag obj, :image, fallback: 'no_image.jpg', size: '150x150', class: 'user-image' %>
  </div>
  <div class="user-profile-box ml-1 mt-3">
    <h5 class="user-data-label">ユーザー名</h5>
    <p class="mb-3 user-data"><%= obj.name %></p>
    <h5 class="user-data-label">筋トレ歴</h5>
    <p class="mb-3 user-data">
      <%if obj.start_date.present? %>
        <%= calc_date_diff(obj.start_date) %>
      <% else %>
        <%= link_to '登録する', edit_user_registration_path(obj) %>
      <% end %>
    </p>
  </div>
</div>

<div class="follow-follower-count-container d-flex justify-content-center">
  <%= render 'users/follow-follower-count-box', resource: obj %>
</div>

<div class="user_infos-count d-flex justify-content-center">
  <div class="user-info mr-4">
      <p class="user-data-label">身長</p>
      <% if obj == current_user %>
        <%= link_to edit_user_path(obj) do %>
          <p class="user-data"><%= obj.tall || '未入力'%>cm</p>
        <% end %>
      <% else %>
        <p class="user-data"><%= obj.tall || '未入力'%>cm</p>
      <% end %>
  </div>
  <div class="user-info">
      <p class="user-data-label">体重</p>
      <% if obj == current_user %>
        <%= link_to edit_user_path(obj) do %>
          <p class="user-data"><%= obj.weight || '未入力'%>kg</p>
        <% end %>
      <% else %>
        <p class="user-data"><%= obj.weight || '未入力'%>kg</p>
      <% end %>
  </div>
  <div class="user-info ml-4">
      <p class="user-data-label">体脂肪率</p>
      <% if obj == current_user %>
        <%= link_to edit_user_path(obj) do %>
          <p class="user-data"><%= obj.body_fat_percentage || '未入力'%>%</p>
        <% end %>
      <% else %>
        <p class="user-data"><%= obj.body_fat_percentage || '未入力'%>%</p>
      <% end %>
  </div>
</div>
<div class="calender-box">
  <%= month_calendar events: obj.records do |date, records| %>
    <%= date.day %>
    <% records.each do |record| %>
      <div>
        <%= link_to record_path(record.id) do %>
          <i class="fas fa-dumbbell" style="color: red;"></i>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>筋トレノート</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="bg-warning pb-2">
        <nav class="navbar navbar-expand-lg col-10 offset-1 p-0">
           <a class="navbar-brand mr-auto" href="/" syle="display: bolck">
             <%= image_tag 'logo.jpg' %>
           </a>
           <button class='navbar-toggler border-dark' type='button' data-toggle='collapse' data-target='#navbarNavDropdown' aria-controls='navbarNavDropdown' aria-expanded='false' aria-label='Toggle navigation'>
             <span class='navbar-toggler-icon'></span>
           </button>
           <div id='navbarNavDropdown' class='collapse navbar-collapse'>
             <% if user_signed_in? %>  <!--ログインしている場合-->
              <ul class="nav navbar-nav ml-auto d-flex align-items-center">
               <li class="nav-item header-nav-item">
                 <%= link_to user_path(current_user), {class: 'nav-link btn btn-danger mr-3 border-dark'} do %>
                 <i class="far fa-id-card text-white font-weight-bold">マイページ</i>
                 <% end %>
               </li>
               <li class="nav-item header-nav-item">
                 <%= link_to records_path, {class: 'nav-link btn btn-danger mr-3 border-dark'} do %>
                   <i class="fas fa-dumbbell text-white font-weight-bold">トレーニング記録</i>
                 <% end %>
               </li>
               <li class="nav-item header-nav-item">
                 <%= link_to user_user_infos_path(current_user.id), {class: 'nav-link btn btn-danger mr-3 border-dark', data: {"turbolinks" => false}} do %>
                   <i class="fas fa-pencil-alt text-white font-weight-bold">体型記録</i>
                 <% end %>
               </li>
               <li class="nav-item header-nav-item">
                 <%= link_to tweets_path, {class: 'nav-link btn btn-danger mr-3 border-dark tubuyaku', data: {"turbolinks" => false}} do %>
                   <i class="far fa-comment-alt text-white font-weight-bold">つぶやく！</i>
                 <% end %>
               </li>
               <li class="nav-item header-nav-item">
                 <%= link_to users_path, {class: 'nav-link btn btn-danger mr-3 border-dark nakama'} do %>
                   <i class="far fa-user-friends text-white font-weight-bold">仲間を探す！</i>
                 <% end %>
               </li>
               <li class="nav-item header-nav-item">
                 <%= link_to notifications_path, {class: 'nav-link btn btn-danger mr-3 border-dark nakama'} do %>
                    <% if unchecked_notifications.any? %>
                      <i class="fa fa-circle" style="color: yellow;"></i>
                    <% end %>
                    <i class="far fa-bell font-weight-bold text-white">通知</i>
                 <% end %>
               </li>
               <li class='nav-item header-nav-item'>
                 <div class="dropdown">
                   <button class="btn btn-warning p-0 dropdown-toggle user-dropdown" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
                    <%= attachment_image_tag current_user, :image, fallback: 'no_image.jpg', size: '50x50', class: 'user-image' %>
                   </button>
                   <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <%= link_to edit_user_registration_path do %>
                        <i class="fas fa-user-cog font-weight-bold dropdown-item p-3"> ユーザー情報編集</i>
                      <% end %>
                      <%= link_to privacy_path do %>
                        <i class="fas fa-info-circle font-weight-bold dropdown-item p-3"> プライバシーポリシー</i>
                      <% end %>
                      <%= link_to term_path do %>
                        <i class="fas fa-file-alt font-weight-bold dropdown-item p-3 pb-4"> 利用規約</i>
                      <% end %>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                        <i class="fas fa-sign-out-alt font-weight-bold dropdown-item p-3 pt-4 border-top sign-out"> ログアウト</i>
                      <% end %>
                   </div>
                 </div>
               </li>
              </ul>
            <% else %> <!--ログインしていない場合-->
              <ul class="nav navbar-nav ml-auto">
               <li class="nav-item header-nav-item">
                 <%= link_to '新規登録', new_user_registration_path, {class: 'nav-link btn btn-danger mr-3 border-dark'} %>
               </li>
               <li class="nav-item header-nav-item">
                 <%= link_to 'ログイン', new_user_session_path, {class: 'nav-link btn btn-danger mr-3 border-dark'} %>
               </li>
              </ul>
            <% end %>
           </div>
        </nav>
        <% if user_signed_in? %>
          
        <% end %>
    
      </div>
    </header>
    
    <div style='height: 72px'>
      
    </div>
    
    <% flash.each do |key, value| %>  <!-- flashの表示　-->
      <% if key == 'alert' || key == 'notice' || key == 'error' %> <!-- deviseのflashメッセージへ対応 -->
        <div class="alert alert-<%= devise_flashkey_to_bootstrap(key) %> m-0">
         <%= value %> 
         <button class='close' data-dismiss='alert' aria-label='close'>
           <span aria-hidden='true'>&times;</span>
         </button>
       </div>
      <% elsif key=='notification' %>
        <div class="alert alert-success m-0">
          <%= link_to '新着通知があります。 詳細はこちら>>', notifications_path %>
         <button class='close' data-dismiss='alert' aria-label='close'>
           <span aria-hidden='true'>&times;</span>
         </button>
       </div>
      <% else %>
       <div class="alert alert-<%= key %> m-0">
         <%= value %> 
         <button class='close' data-dismiss='alert' aria-label='close'>
           <span aria-hidden='true'>&times;</span>
         </button>
       </div>
      <% end %>
    <% end %>
    
    <%= yield %>
    
    <div id='top-up-btn'>
      <i class="fas fa-4x fa-arrow-circle-up"></i>
    </div>
    
    <footer class= 'py-2 text-center'>
      <span>@2021 筋トレノート</span>
    </footer>
  </body>
</html>